### ISSUE TITLE
点击查询好久没有反应

### ISSUE THREAD

**Issue by yxy823** [l1422586361/widget-graph#1]
![image](https://user-images.githubusercontent.com/38773494/200341017-0fc50466-004d-48c9-bb9c-dd2eb88fab8b.png)

**Comment by yxy823** [comment]
这种是没有执行成功吗？

**Comment by l1422586361** [comment]
重建索引试下，不行看下版本，我开发调试的版本是2.4.3

**Comment by yxy823** [comment]
![image](https://user-images.githubusercontent.com/38773494/200611646-6bd69d6c-f82c-42f5-a22c-b488b5ac0696.png)
换成 2.4.3 还是不行哦

**Comment by l1422586361** [comment]
报错看上去是没有找到索引，重建索引试过没？

**Comment by yxy823** [comment]
![image](https://user-images.githubusercontent.com/38773494/200866591-407a1912-e67a-479d-b117-d48fb0d1b9e1.png)
重建过了，这个报错应该是通过api没有请求到数据，是还需要其他设置吗

**Comment by yxy823** [comment]
![Uploading image.png…]()
返回401状态码

**Comment by yxy823** [comment]
我给config.js 手动增加了token

**Comment by yxy823** [comment]
![image](https://user-images.githubusercontent.com/38773494/200871782-cba1cb08-e963-4a13-87c7-d2cda24afadb.png)

**Comment by l1422586361** [comment]
跟token没关系，调用的也是通过SQL调取索引数据的接口，有问题只能是索引没数据导致的，想不出其他什么原因
