### ISSUE TITLE
点击全局关系图后无法还原回局部关系图

### ISSUE THREAD

**Issue by lindroy** [l1422586361/widget-graph#3]
首先感谢作者的付出，提个小bug：点击了全局关系图按钮，会显示为全局关系图，但是无法还原回局部关系图了。

**Comment by l1422586361** [comment]
可以先保存成文件，后面再加载进来。前进后退功能限于我的技术还在研究接口逻辑，也是刚入门

**Comment by lindroy** [comment]
理解的，加油。我用这个插件的目的主要是要看当前文档与其他文档的关系（毕竟官方没有正链，而且你的比官方的要顺滑），并不关心全局关系图。顺便问一句，你有打算做这种类似于列表形式的吗？关系图虽然直观，但是多了不好查找。
<img width="281" alt="image" src="https://user-images.githubusercontent.com/22363769/212221034-ccf42f35-26b1-4eeb-866a-7d4679af4f21.png">

**Comment by l1422586361** [comment]
嗯，感谢理解，这个做起来不难，不过现在在转用vue迁移实现，可以期待下

**Comment by lindroy** [comment]
> 

好的，多谢。

**Comment by l1422586361** [comment]
> 

新发布的版本已添加这个面板

**Comment by lindroy** [comment]
我刚刚试了最新的版本，暗黑模式下文字是黑色，有点看不清楚，建议改成白色或者灰色。另外，”超级节点高亮“没有效果了。

**Comment by l1422586361** [comment]
嗯，暗黑模式回头研究下，高亮和保存两个目前看都有些问题，有时又是正常的，需要再研究下
